{{- if .Values.ingress.enabled }}
{{- $fullName := include "chart-app.fullname" . -}}
{{- $servicePort := .Values.service.port -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "chart-app.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  ingressClassName: {{ .Values.ingress.className | default "nginx" }}
  {{- if .Values.ingress.tls }}
  tls:
    {{- range .Values.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      {{- if .secretName }}
      secretName: {{ .secretName }}
      {{- end }}
    {{- end }}
  {{- end }}
  rules:
    {{ if .Values.ingress.customHosts }}
      {{- range .Values.ingress.customHosts }}
      - host: {{ .host | quote }}
        http:
          paths:
            {{- range .paths }}
            - path: {{ .path }}
              pathType: Prefix
              backend:
                service:
                  name: {{ .service }}
                  port:
                    number: {{ .port }}
            {{- end }}
      {{- end }}
    {{ else }}
      {{- range .Values.ingress.hosts }}
      - host: {{ .host | quote }}
        http:
          paths:
            {{- range .paths }}
            - path: {{ . }}
              pathType: Prefix
              backend:
                service:
                  name: {{ $fullName }}
                  port:
                    number: {{ $servicePort }}
            {{- end }}
      {{- end }}
    {{ end }}
{{- end }}
