{{ if .Values.persistentVolume -}}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.fullnameOverride }}-pv
  {{ if .Values.persistentVolume.namespace }}
  namespace: {{ .Values.persistentVolume.namespace }}
  {{ end }}
  labels:
    {{- include "chart-app.labels" . | nindent 4 }}
spec:
  accessModes:
    {{- range .Values.persistentVolume.storageClass.accessModes }}
    - {{ . }}
    {{- end }}
  capacity:
    storage: {{ .Values.persistentVolume.storageClass.storage }}
  claimRef:
    name: {{ .Values.fullnameOverride }}-pvc
    {{ if .Values.persistentVolume.namespace }}
    namespace: {{ .Values.persistentVolume.namespace }}
    {{ end }}
  storageClassName: {{ .Values.fullnameOverride }}
  {{- if .Values.persistentVolume.mountOptions }}
  mountOptions:
    {{- range .Values.persistentVolume.mountOptions }}
    - {{ . }}
    {{- end }}
  {{- end }}
  {{- if .Values.persistentVolume.persistentVolumeReclaimPolicy }}
  persistentVolumeReclaimPolicy: {{ .Values.persistentVolume.persistentVolumeReclaimPolicy }}
  {{- end }}
  {{- if .Values.persistentVolume.csi }}
  csi:
    driver: gcsfuse.csi.storage.gke.io
    volumeHandle: {{ .Values.persistentVolume.csi.volumeHandle }}
    readOnly: {{ .Values.persistentVolume.csi.readOnly }}
  {{- end }}
  {{- if .Values.persistentVolume.nfs }}
  nfs:
    path: {{ .Values.persistentVolume.nfs.path }}
    server: {{ .Values.persistentVolume.nfs.server }}
    readOnly: {{ .Values.persistentVolume.nfs.readOnly }}
  {{- end }}
{{ end -}}
