{{ if .Values.persistentVolume -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.fullnameOverride }}-pvc
  namespace: {{ .Values.persistentVolume.namespace }}
  labels:
    {{- include "chart-app.labels" . | nindent 4 }}
spec:
  accessModes:
    {{- range .Values.persistentVolume.storageClass.accessModes }}
    - {{ . }}
    {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistentVolume.storageClass.storage }}
  volumeName: {{ .Values.fullnameOverride }}-pv
  storageClassName: {{ .Values.fullnameOverride }}
{{ end -}}
