{{ if .Values.persistentVolume -}}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.fullnameOverride }}-pv
  labels:
    {{- include "chart-app.labels" . | nindent 4 }}
spec:
  accessModes:
    {{- range .Values.persistentVolume.storageClass.accessModes }}
    - {{ . }}
    {{- end }}
  capacity:
    storage: {{ .Values.persistentVolume.storageClass.storage }}
  storageClassName: {{ .Values.fullnameOverride }}
  # claimRef:
  #   name: {{ .Values.fullnameOverride }}-pvc
  {{- if .Values.persistentVolume.mountOptions }}
  mountOptions:
    {{- range .Values.persistentVolume.mountOptions }}
    - {{ . }}
    {{- end }}
  {{- end }}
  {{- if .Values.persistentVolume.csi }}
  csi:
    driver: gcsfuse.csi.storage.gke.io
    volumeHandle: {{ .Values.persistentVolume.csi.volumeHandle }}
    readOnly: {{ .Values.persistentVolume.csi.readOnly }}
  {{- end }}
{{ end -}}
