{{- if .Values.secrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{.Values.fullnameOverride}}
  labels:
    {{- include "chart-app.labels" . | nindent 4 }}
type: Opaque
data:
{{- with .Values.secrets }}
  {{- toYaml . | nindent 2 }}
{{- end }}
{{- end }}
