controller:
  volumes:
  - name: canon-site-boston-cache
    persistentVolumeClaim:
      claimName: canon-site-boston-cache-pvc

  volumeMounts:
    - mountPath: /opt/sfw/boston
      name: canon-site-boston-cache
      subPath: boston-06122024

  service:
    loadBalancerIP: 34.27.24.41

  replicaCount: 2
