controller:
  volumes:
  - name: canon-site-boston-cache
    persistentVolumeClaim:
      claimName: nginx-ingress-canon-cache-pvc

  volumeMounts:
    - mountPath: /opt/sfw/boston
      name: canon-site-boston-cache
      subPath: boston-06122024
    - mountPath: /opt/sfw/cambridge
      name: canon-site-cambridge-cache
      subPath: cambridge-12082024

  service:
    loadBalancerIP: 34.27.24.41

  replicaCount: 2
