kind: ConfigMap
apiVersion: v1
metadata:
  name: nginx-ingress-canon
data:
  server-tokens: "false"
  http-snippets: |
    proxy_cache_path /opt/sfw levels=1:2 keys_zone=cambridge-cache:1g max_size=160g inactive=365d use_temp_path=off;

    map $http_host $served_host {
      default $http_host;
      cambridge-app.datausa.io prod-app.datausa.io;
      datausa.io prod-app.datausa.io;
    }

    map $request_method:$request_uri $response_xframe_option {
    default "SAMEORIGIN";
     "~GET:\/profile\/[a-z]+\/[a-z-]+\/[a-z-]+\/[a-z-]+" "";
    }

    gzip on;
    gzip_types text/plain application/javascript application/x-javascript text/css application/xml image/svg+xml;
    gzip_vary on;
