kind: ConfigMap
apiVersion: v1
metadata:
  name: nginx-ingress
  namespace: nginx-ingress
data:
  server-tokens: "false"
  http-snippets: |
    proxy_cache_path /opt/sfw levels=1:2 keys_zone=test_cache:75m max_size=300m inactive=365d use_temp_path=off;

    map $http_host $served_host {
      default $http_host;
      datausa.io arkansas-app.datausa.io;
      datausa.io boston-app.datausa.io;
    }
