kind: ConfigMap
apiVersion: v1
metadata:
  name: nginx-ingress-canon
data:
  server-tokens: "false"
  http-snippets: |
    map $http_host $served_host {
      default $http_host;
      prod.datausa.io boston-app.datausa.io;
    }

    gzip on;
