image:
  pullPolicy: Always

imagePullSecrets:
  - name: github

replicaCount: 3

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 4
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 120

resources:
  requests:
    cpu: 100m
    memory: 1Gi
    ephemeral-storage: 100Mi
  limits:
    cpu: 500m
    memory: 2Gi
    ephemeral-storage: 512Mi

livenessProbe:
  failureThreshold: 3
  httpGet:
    path: /
    port: 3300
    scheme: HTTP
  initialDelaySeconds: 40
  periodSeconds: 30
  timeoutSeconds: 30
  successThreshold: 1

readinessProbe:
  failureThreshold: 3
  httpGet:
    path: /
    port: 3300
    scheme: HTTP
  initialDelaySeconds: 40
  periodSeconds: 30
  timeoutSeconds: 30
  successThreshold: 2

podAnnotations:
  gke-gcsfuse/volumes: "true"
  gke-gcsfuse/cpu-limit: 500m
  gke-gcsfuse/memory-limit: 512Mi
  gke-gcsfuse/ephemeral-storage-limit: 2Gi

volumesEnabled: true

volumes:
  - name: google-analytics-volumen
    configMap:
      name: google-analytics
  - name: nginx-cache-volume
    persistentVolumeClaim:
      claimName: canon-site-arkansas-pvc

volumeMountsEnabled: true

volumeMounts:
  - name: google-analytics-volumen
    mountPath: /app/google
  - name: nginx-cache-volume
    mountPath: /tmp/nginx-cache
    readOnly: false

persistentVolume:
  storageClass:
    accessModes:
      - ReadWriteMany
    storage: 30Gi
    storageClassName:
  mountOptions:
    - implicit-dirs
    - uid=1001
    - gid=1001
  csi:
    volumeHandle: datausa-site-cache # bucket name
    readOnly: false

securityContext:
  capabilities: {}
  privileged: true

podSecurityContext:
  runAsUser: 1001
  runAsGroup: 1001
  fsGroup: 1001

service:
  type: ClusterIP
  port: 3300

serviceAccount:
  # Specifies whether a service account should be created
  create: false
  # Annotations to add to the service account
  annotations:
    iam.gke.io/gcp-service-account: bucket-admin@data-usa-174910.iam.gserviceaccount.com
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: "kube-httpcache"

configMap:
  CANON_API: "https://app-arkansas.datausa.io"
  CANON_CMS_CUBES: "https://arkansas-api.datausa.io/"
  CANON_CMS_ENABLE: "false"
  CANON_CMS_FORCE_HTTPS: "true"
  CANON_CMS_GENERATOR_TIMEOUT: "600000"
  CANON_CMS_LOGGING: "true"
  CANON_CMS_MINIMUM_ROLE: "1"
  CANON_CMS_REQUESTS_PER_SECOND: "60"
  CANON_CONST_CART: "datausa-cart-v3"
  CANON_CONST_CUBE: "https://arkansas-api.datausa.io/"
  CANON_CONST_TESSERACT: "https://api-ts-arkansas.datausa.io/"
  CANON_DB_NAME: "datausa-cms-21"
  CANON_DB_USER: "deploy"
  CANON_GEOSERVICE_API : "https://geoservice.datausa.io/api/"
  CANON_GOOGLE_ANALYTICS: "UA-70325841-1"
  CANON_LANGUAGES: "en"
  CANON_LANGUAGE_DEFAULT: "en"
  CANON_LOGICLAYER_CUBE: "https://arkansas-api.datausa.io/"
  CANON_LOGICLAYER_SLUGS: "true"
  CANON_LOGINS: "true"
  GA_KEYFILE: "/app/google/googleAnalyticsKey.json"

ingress:
  enabled: true
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    acme.cert-manager.io/http01-edit-in-place: "true"
    ingress.kubernetes.io/ssl-redirect: "false"
    nginx.org/client-max-body-size: "500m"
    nginx.org/proxy-connect-timeout: "300s"
    nginx.org/proxy-read-timeout: "300s"
    nginx.org/proxy-buffers: "8 32k"
    nginx.org/proxy-buffer-size: "32k"
    nginx.org/proxy-busy-buffers-size: "128k"
    nginx.org/websocket-services: "canon-site-arkansas"
    nginx.org/location-snippets: |
      add_header Access-Control-Allow-Origin *;
    nginx.org/server-snippets: |
      if ($http_x_forwarded_proto = 'http') {
          return 308 https://$host$request_uri;
      }
  customHosts:
    - host: app-arkansas.datausa.io
      paths:
        - path: /
          service: canon-site-arkansas
          port: 3300
        - path: /api/candidate/
          service: canon-site-arkansas
          port: 3300
        - path: /api/civic/
          service: canon-site-arkansas
          port: 3300
        - path: /api/generators/
          service: canon-site-arkansas
          port: 3300
        - path: /api/materializers/
          service: canon-site-arkansas
          port: 3300
        - path: /api/cms/
          service: canon-site-arkansas
          port: 3300
        - path: /api/cms/customAttributes
          service: canon-site-arkansas
          port: 3300
        - path: /ws
          service: canon-site-arkansas
          port: 3300
  tls:
    - secretName: canon-site-ingress-tls
      hosts:
        - app-arkansas.datausa.io
