image:
  pullPolicy: Always

imagePullSecrets:
  - name: github

replicaCount: 3

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 120

resources:
  requests:
    cpu: 128m
    memory: 1Gi
  limits:
    cpu: 500m
    memory: 6Gi

livenessProbe:
  failureThreshold: 3
  httpGet:
    path: /
    port: 3300
    scheme: HTTP
  initialDelaySeconds: 40
  periodSeconds: 30
  timeoutSeconds: 30
  successThreshold: 1

readinessProbe:
  failureThreshold: 3
  httpGet:
    path: /
    port: 3300
    scheme: HTTP
  initialDelaySeconds: 40
  periodSeconds: 30
  timeoutSeconds: 30
  successThreshold: 2

volumeMountsEnabled: true

volumeMounts:
  name: google-analytics-volumen
  mountPath: /app/google

volumesEnabled: true

volumes:
  name: google-analytics-volumen
  configMap:
    name: google-analytics

service:
  type: ClusterIP
  port: 3300

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

configMap:
  CANON_API: "https://datausa.io"
  CANON_CMS_CUBES: "https://arkansas-api.datausa.io/"
  CANON_CMS_ENABLE: "true"
  CANON_CMS_FORCE_HTTPS: "true"
  CANON_CMS_GENERATOR_TIMEOUT: "600000"
  CANON_CMS_LOGGING: "true"
  CANON_CMS_MINIMUM_ROLE: "1"
  CANON_CMS_REQUESTS_PER_SECOND: "60"
  CANON_CONST_CART: "datausa-cart-v3"
  CANON_CONST_CUBE: "https://arkansas-api.datausa.io/"
  CANON_CONST_TESSERACT: "https://api.datausa.io/"
  CANON_DB_NAME: "datausa-cms-21"
  CANON_DB_USER: "deploy"
  CANON_GEOSERVICE_API : "https://geoservice.datausa.io/"
  CANON_GOOGLE_ANALYTICS: "UA-70325841-1"
  CANON_LANGUAGES: "en"
  CANON_LANGUAGE_DEFAULT: "en"
  CANON_LOGICLAYER_CUBE: "https://arkansas-api.datausa.io/"
  CANON_LOGICLAYER_SLUGS: "true"
  CANON_LOGINS: "true"
  GA_KEYFILE: "/app/google/googleAnalyticsKey.json"

ingress:
  enabled: true
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    acme.cert-manager.io/http01-edit-in-place: "true"
    ingress.kubernetes.io/ssl-redirect: "false"
    nginx.org/proxy-connect-timeout: "480s"
    nginx.org/proxy-read-timeout: "480s"
    nginx.org/proxy-buffers: "8 16k"
    nginx.org/proxy-buffer-size: "16k"
    nginx.org/proxy-busy-buffers-size: "64k"
    nginx.org/websocket-services: "canon-site"
    nginx.org/location-snippets: |
      add_header Access-Control-Allow-Origin *;
    nginx.org/server-snippets: |
      if ($http_x_forwarded_proto = 'http') {
          return 308 https://$host$request_uri;
      }
  customHosts:
    - host: app-prod.datausa.io
      paths:
        - path: /
          service: cache-site-service
          port: 80
        - path: /signaller
          service: cache-site-service
          port: 8090
        - path: /api/cms
          service: canon-site
          port: 3300
        - path: /api/cms/customAttributes
          service: canon-site
          port: 3300
        - path: /ws
          service: canon-site
          port: 3300
  tls:
    - secretName: canon-site-ingress-tls
      hosts:
        - app-prod.datausa.io
